# Generated by Django 4.2.16 on 2024-11-14 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bucketlistitem_alter_profile_profilepic_and_more'),
        ('users', '0004_rename_author_post_user_post_created_at'),
    ]

    operations = [
    ]
