# Generated by Django 4.2.16 on 2024-12-12 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_rename_caption_post_content_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlistitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bucketlistitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.bucketlistitem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='users.bucketlistitem'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='assigned_tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks_assigned', to='users.bucketlistitem'),
        ),
    ]
